# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. We will try and get back to you as soon as possible.

  Please make sure you have given us as much context as possible.

  To our contributors, Issues marked 'Ready for Dev' are available to claim, just let us know with a reply if you want to claim this issue.

pullRequestOpened: >
  Thank your for raising your pull request.

  Please make sure you have followed our contributing guidelines. We will review it as soon as possible
